#!/bin/bash
ROOT=$(dirname "$(dirname "$(readlink -f "$0")")")
cd $ROOT/www

npm --registry=https://registry.npm.taobao.org \
    --cache=$HOME/.npm/.cache/cnpm \
    --disturl=https://npm.taobao.org/dist \
    --userconfig=$HOME/.cnpmrc \
    install

npm run build

vim -c "set fileencoding=cp936" dist/index.html -c wq
